version: "3.1"
services:
  mongo:
    image: mongo:3.2.4
    restart: always
    ports:
      - 27017:27017

  # APP  ***************************************************************************************
  demo:
    image: anakromeiro/url_shortener_challenge
    ports:
      - 8080:8080
    links:
      - mongo
    depends_on:
      - mongo